language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  edge: true
  api_key:
    secure: nPq3LJ76VFTJR0jmMHdAxHEkmLp61dEwn8jv/vKE+3lzRN5zNgkl56A13fXh+Uo6vYg4Tm9ogduPgQ35THCPQeP0ns26U1a7tAf1tGKyVB2GCEL0zlWNVG4RZI+sUI8Qmt9pMOgkRcBiqfsqVFUe1P+aBEMj0vym7NsOysMfpC6rsIzXCz58VKZ7X4jqb+252H1lmQVrEZsqPW8Rxzmc7zSOGgkhn49lbmiv/d6gJJGbF1Di057AaiSBA3EBPcG+TWacCVFVmlX12KUzAxSdlG8PbjTUuqXa+avk2AqbOsgdVBwOFsRiTJduWkNgIUe6YvNrB3xbspoJHsqEU1yhTd0JlLMdtcAvl2YVGZx7lQF4c/CI4YPlw6GNvWWT00tS6KqlI3o+UCu9r5SU4aIWP5sqMD8ILQzi5/JHqoAqAdsc61gRwzHu6yyqQ+xp6/huZajh+vefbjAzl27e4PwVkiaGi8bLvrogTIBGg5dBJ6sC7DRker20aXstj3Om9tylxmC7U3dwI7LuiAUhB3hA6+XzN+ph1me+NxfoJCju0eW2VVh9IRIZJ14c4uxCaPby/orTIX17jYrK2kxl+9fVpmMTk4GYbdvBiG4SPDmBfhinRbLUHCEoFWmr22d7rwBZVZ0IhhqeJZVqtrgqoec7CWf98FpyI/05jPMGARBcr9s=
  app: dry-beyond-32984
  on:
    repo: davepatel95/blog-app-mongoose-challenge-solution
